services:
  api-simulador:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-simulador-hackathon
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Configurações JVM otimizadas para container
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication
      # Perfil Spring
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=America/Sao_Paulo
      
      # Configurações SQL Server Principal
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_URL=jdbc:sqlserver://${DB_URL}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_PASSWORD=${DB_PASSWORD}
      
      # Configurações H2 para desenvolvimento
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_URL=${H2_URL}
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_USERNAME=${H2_USERNAME}
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_PASSWORD=${H2_PASSWORD}
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      
      # Configurações Azure Event Hub  
      - AZURE_EVENTHUB_CONNECTION-STRING=${AZURE_EVENTHUB_CONNECTION_STRING}
      - AZURE_EVENTHUB_ENTITY-PATH=${AZURE_EVENTHUB_ENTITY_PATH}
      - AZURE_EVENTHUB_NAME=${AZURE_EVENTHUB_NAME}
      - AZURE_EVENTHUB_ENABLED=true
      
      # Configurações Logging
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=${SHOW_SQL}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_BR_COM_LEO=DEBUG

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - simulador-network
    volumes:
      # Volume para logs persistentes (opcional)
      - ./logs:/app/logs:rw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "project=hackathon-2025"
      - "service=api-simulador"
      - "version=1.0.0"

networks:
  simulador-network:
    driver: bridge