services:
  api-simulador:
    build: .
    container_name: api-simulador
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Configurações JVM
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
      # Perfil Spring
      - SPRING_PROFILES_ACTIVE=prod
      
      # Configurações SQL Server Principal
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_URL=jdbc:sqlserver://${DB_URL}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PRINCIPAL-SQLSERVER_PASSWORD=${DB_PASSWORD}
      
      # Configurações H2
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_URL=${H2_URL}
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_USERNAME=${H2_USERNAME}
      - SPRING_SECOND-DATASOURCE_LOCAL-H2_PASSWORD=${H2_PASSWORD}
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      
      # Configurações Azure Event Hub  
      - AZURE_EVENTHUB_CONNECTION-STRING=${AZURE_EVENTHUB_CONNECTION_STRING}
      - AZURE_EVENTHUB_ENTITY-PATH=${AZURE_EVENTHUB_ENTITY_PATH}
      - AZURE_EVENTHUB_NAME=${AZURE_EVENTHUB_NAME}
      - AZURE_EVENTHUB_ENABLED=true
      
      # Configurações Logging
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=${SHOW_SQL}

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - simulador-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - simulador-network
    depends_on:
      - api-simulador

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - simulador-network
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  simulador-network:
    driver: bridge