# Configuração Geral
server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-simulador
  
  main:
    banner-mode: off

  # Configuração SQL Server
  datasource:
    principal-sqlserver:
      jdbc-url: jdbc:sqlserver://${DB_URL}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 1200000

  # Configuração H2
  second-datasource:
    local-h2:
      jdbc-url: ${H2_URL:jdbc:h2:mem:simulacao};DB_CLOSE_DELAY=-1
      username: ${H2_USERNAME:sa}
      password: ${H2_PASSWORD:password}
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
        web-admin-password: ${H2_ADMIN_PASSWORD:admin}

  # Configuração JPA
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never

# Configuração de Monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      access: UNRESTRICTED
    prometheus:
      access: UNRESTRICTED

# Configuração do Azure Event Hub
azure:
  eventhub:
    connection-string: ${AZURE_EVENTHUB_CONNECTION_STRING}
    entity-path: ${AZURE_EVENTHUB_ENTITY_PATH}
    name: ${AZURE_EVENTHUB_NAME}
    enabled: true

logging:
  level:
    org.hibernate.SQL: ${SHOW_SQL:false}