# Configuração Geral
server:
  port: 8080

spring:
  application:
    name: api-simulador

  # Configuração Principal (SQL Server)
  principal-sqlserver:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://dbhackathon.database.windows.net:1433;databaseName=hack;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: hack
      password: Password23
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 1200000
    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default_schema: dbo
          dialect: org.hibernate.dialect.SQLServerDialect
          show_sql: false
          format_sql: true
          jdbc.time_zone: UTC

  # Configuração Local (H2)
  local-h2:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:simulacao;DB_CLOSE_DELAY=-1
      username: sa
      password: password
    jpa:
      open-in-view: false
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show_sql: true
          format_sql: true
          jdbc.time_zone: UTC

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never

  main:
    banner-mode: off

  datasource:
    principal-sqlserver:
      jdbc-url: jdbc:sqlserver://dbhackathon.database.windows.net:1433;databaseName=hack;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: hack
      password: Password23
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 1200000

  second-datasource:
    local-h2:
      jdbc-url: jdbc:h2:mem:simulacao;DB_CLOSE_DELAY=-1
      username: sa
      password: password
      driver-class-name: org.h2.Driver

# Configuração do Azure Event Hub
azure:
  eventhub:
    connection-string: Endpoint=sb://eventhack.servicebus.windows.net/;SharedAccessKeyName=hack;SharedAccessKey=HeHeVaVqyVkntO2FnjQcs2Ilh/4MUDo4y+AEhKp8z+g=;EntityPath=simulacoes
    entity-path: simulacoes
    name: simulacoes
    enabled: true  # mude para false para desabilitar

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    br.com.leo.apisimulador: DEBUG