global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'api-simulador'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-simulador:8080']